project:
  type: website
  output-dir: docs
  post-render:
    - ./generate-pdfs.sh

website:
  title: "Data Donation Studies: SPP Annual Meeting Workshop"
  navbar:
    search: false
    pinned: true
    tools:
      - icon: github
        href: https://github.com/frodew/workshop_spp_annual_meeting
      - icon: website
        href: https://data-donation-science.de

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
